# Generated by Django 5.0.3 on 2024-03-28 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=70)),
                ('ville', models.CharField(max_length=30)),
                ('codePostal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Amis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAjout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateField()),
                ('id_Amis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.amis')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('images', models.JSONField(default=list)),
                ('localisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse')),
                ('id_ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.attraction')),
            ],
        ),
        migrations.CreateModel(
            name='Restauration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialite', models.CharField(max_length=30)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('destinations', models.ManyToManyField(to='DashboardAPI.destination')),
                ('evenements', models.ManyToManyField(to='DashboardAPI.evenement')),
                ('hebergements', models.ManyToManyField(to='DashboardAPI.hebergement')),
                ('restaurations', models.ManyToManyField(to='DashboardAPI.restauration')),
                ('transports', models.ManyToManyField(to='DashboardAPI.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('attraction', models.ManyToManyField(to='DashboardAPI.attraction')),
                ('destinations', models.ManyToManyField(to='DashboardAPI.destination')),
                ('evenements', models.ManyToManyField(to='DashboardAPI.evenement')),
                ('hebergements', models.ManyToManyField(to='DashboardAPI.hebergement')),
                ('restaurations', models.ManyToManyField(to='DashboardAPI.restauration')),
                ('transports', models.ManyToManyField(to='DashboardAPI.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=30)),
                ('dateN', models.DateField()),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('id_adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoie', models.DateField()),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=20)),
                ('offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.offre')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.promotion')),
                ('id_destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='DashboardAPI.utilisateur')),
                ('id_recepteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='DashboardAPI.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Message_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoie', models.DateField()),
                ('message', models.CharField(max_length=500, null=True)),
                ('convertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.conversation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=300, null=True)),
                ('type', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='amis',
            name='id_amis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis_as_friend', to='DashboardAPI.utilisateur'),
        ),
        migrations.AddField(
            model_name='amis',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis_as_user', to='DashboardAPI.utilisateur'),
        ),
    ]
