# Generated by Django 5.0.3 on 2024-04-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='codePostal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='rue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='serie',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateN',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id_adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
