# Generated by Django 5.0.3 on 2024-04-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0002_alter_adresse_codepostal_alter_adresse_rue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='codePostal',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='rue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='serie',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateN',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id_adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardAPI.adresse'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
