# Generated by Django 5.0.3 on 2024-04-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0007_remove_utilisateur_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='token',
        ),
    ]
