# Generated by Django 5.0.3 on 2024-04-21 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0010_remove_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
