# Generated by Django 5.0.3 on 2024-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0012_alter_destination_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Data/destination_images/'),
        ),
    ]
