# Generated by Django 5.0.3 on 2024-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0014_alter_destination_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
