# Generated by Django 5.0.3 on 2024-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0015_evenement_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='time',
            new_name='time_debut',
        ),
        migrations.AddField(
            model_name='evenement',
            name='time_fin',
            field=models.TimeField(null=True),
        ),
    ]
