# Generated by Django 5.0.3 on 2024-04-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0016_rename_time_evenement_time_debut_evenement_time_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id_Amis',
        ),
        migrations.AddField(
            model_name='conversation',
            name='destinatair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinataire', to='DashboardAPI.utilisateur'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='recepteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepteur', to='DashboardAPI.utilisateur'),
        ),
    ]
