# Generated by Django 5.0.3 on 2024-04-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0018_message_line_time_envoie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='DashboardAPI.destination'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='evenements',
            field=models.ManyToManyField(blank=True, to='DashboardAPI.evenement'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='hebergements',
            field=models.ManyToManyField(blank=True, to='DashboardAPI.hebergement'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='restaurations',
            field=models.ManyToManyField(blank=True, to='DashboardAPI.restauration'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='transports',
            field=models.ManyToManyField(blank=True, to='DashboardAPI.transport'),
        ),
    ]
