# Generated by Django 5.0.3 on 2024-04-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0020_remove_ligne_activite_date_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_activite',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='ligne_activite',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='ligne_activite',
            name='evenements',
        ),
        migrations.RemoveField(
            model_name='ligne_activite',
            name='hebergements',
        ),
        migrations.RemoveField(
            model_name='ligne_activite',
            name='restaurations',
        ),
        migrations.RemoveField(
            model_name='ligne_activite',
            name='transports',
        ),
        migrations.AddField(
            model_name='ligne_activite',
            name='id_attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.attraction'),
        ),
        migrations.AddField(
            model_name='ligne_activite',
            name='id_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.destination'),
        ),
        migrations.AddField(
            model_name='ligne_activite',
            name='id_evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.evenement'),
        ),
        migrations.AddField(
            model_name='ligne_activite',
            name='id_hebergement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.hebergement'),
        ),
        migrations.AddField(
            model_name='ligne_activite',
            name='id_restauration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.restauration'),
        ),
        migrations.AddField(
            model_name='ligne_activite',
            name='id_transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardAPI.transport'),
        ),
    ]
