# Generated by Django 5.0.3 on 2024-04-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0021_remove_ligne_activite_attraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='DashboardAPI.utilisateur'),
        ),
    ]
