# Generated by Django 5.0.3 on 2024-05-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0024_remove_conversation_user_conversation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_line',
            old_name='convertation',
            new_name='convertation_id',
        ),
    ]
