# Generated by Django 5.0.3 on 2024-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0025_rename_convertation_message_line_convertation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_line',
            name='message',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
