# Generated by Django 5.0.3 on 2024-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAPI', '0028_alter_destination_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
