

export const ALL_DESTINATION = 'ALL_DESTINATION'
export const POPULAR_DESTINATION = 'POPULAR_DESTINATION'
export const DESTINATION_BY_ID = 'DESTINATION_BY_ID'
export const GET_ERROR_DESTINATION = 'GET_ERROR_DESTINATION'

export const ALL_ATTRACTION = 'ALL_ATTRACTION'
export const GET_ERROR_ATTRACTION = 'GET_ERROR_ATTRACTION'


export const ALL_EVENEMENT = 'ALL_EVENEMENT'
export const GET_ERROR_EVENEMENT = 'GET_ERROR_EVENEMENT'

export const ALL_HEBERGEMENT = 'ALL_HEBERGEMENT'
export const GET_ERROR_HEBERGEMENT = 'GET_ERROR_HEBERGEMENT'


export const AVIS_OF_DESTINATION = 'AVIS_OF_DESTINATION'
export const GET_ERROR_AVIS = 'GET_ERROR_AVIS'


export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_ERROR = 'REGISTER_ERROR'


export const ALL_CONVERSATION_OF_USER = "ALL_CONVERSATION_OF_USER"
export const GET_ERROR_CONVERSATION = "GET_ERROR_CONVERSATION"



// Chat Bot  
export const MESSAGE_RESPONSE = "MESSAGE_RESPONSE"
export const MESSAGE_RESPONSE_ERR = "MESSAGE_RESPONSE_ERR"
export const ALL_MESSSAGES_CONVERSATION = "ALL_MESSSAGES_CONVERSATION"
export const ALL_MESSSAGES_CONVERSATION_ERR = "ALL_MESSSAGES_CONVERSATION_ERR"


// Chat 
export const ALL_MESSSAGES_CONVERSATION_CHAT = "ALL_MESSSAGES_CONVERSATION_CHAT"
export const ALL_MESSSAGES_CONVERSATION_CHAT_ERR = "ALL_MESSSAGES_CONVERSATION_CHAT_ERR"


export const NAME_FRIEND = "NAME_FRIEND"
export const NAME_FRIEND_ERR = "NAME_FRIEND_ERR"









