

export const ALL_DESTINATION = 'ALL_DESTINATION'
export const GET_ERROR_DESTINATION = 'GET_ERROR_DESTINATION'


export const ID_ADRESSE = 'ID_ADRESSE'
export const GET_ERROR_ADRESSE = 'GET_ERROR_ADRESSE'
